usr/bin/nvvp
usr/libnvvp/.eclipseproduct		usr/lib/nvidia-visual-profiler/
usr/libnvvp/*.html			usr/share/nvidia-visual-profiler/
usr/libnvvp/*.xml			usr/share/nvidia-visual-profiler/
usr/libnvvp/configuration		usr/share/nvidia-visual-profiler/
usr/libnvvp/features			usr/share/nvidia-visual-profiler/
usr/libnvvp/icon.xpm			usr/share/nvidia-visual-profiler/
usr/libnvvp/nvvp			usr/lib/nvidia-visual-profiler/
usr/libnvvp/nvvp.ini			usr/lib/nvidia-visual-profiler/
usr/libnvvp/p2				usr/share/nvidia-visual-profiler/
usr/libnvvp/plugins/*			usr/share/nvidia-visual-profiler/plugins/
usr/libnvvp/plugins-arch/*		usr/lib/nvidia-visual-profiler/plugins/
usr/libnvvp/readme			usr/share/nvidia-visual-profiler/
