#!/usr/bin/dh-exec --with=filter
cuda/bin/bin2c							usr/bin/
cuda/bin/crt/link.stub						usr/lib/nvidia-cuda-toolkit/bin/crt/
cuda/bin/crt/prelink.stub					usr/lib/nvidia-cuda-toolkit/bin/crt/
cuda/bin/cudafe++						usr/bin/
cuda/bin/cuda-memcheck						usr/bin/
cuda/bin/cuobjdump						usr/bin/
cuda/bin/fatbinary						usr/bin/
cuda/bin/nvdisasm						usr/bin/
cuda/bin/nvlink							usr/bin/
cuda/bin/nvprune						usr/bin/
cuda/bin/ptxas							usr/bin/

cuda/bin/nvcc							usr/lib/nvidia-cuda-toolkit/bin/
debian/nvcc							usr/bin/
cuda/bin/nvcc.profile						etc/
debian/gcc							usr/lib/nvidia-cuda-toolkit/bin/
debian/g++							usr/lib/nvidia-cuda-toolkit/bin/

cuda/nvvm/bin/cicc						usr/lib/nvidia-cuda-toolkit/nvvm/bin/
cuda/nvvm/lib64/libnvvm.so.3					usr/lib/nvidia-cuda-toolkit/nvvm/lib64/
cuda/nvvm/lib64/libnvvm.so.3.*					usr/lib/nvidia-cuda-toolkit/nvvm/lib64/
cuda/nvvmx/bin/cicc						usr/lib/nvidia-cuda-toolkit/nvvmx/bin/
cuda/nvvmx/lib64/libnvvm.so.3					usr/lib/nvidia-cuda-toolkit/nvvmx/lib64/
cuda/nvvmx/lib64/libnvvm.so.3.*					usr/lib/nvidia-cuda-toolkit/nvvmx/lib64/
cuda/nvvm/include/nvvm.h					usr/include/
cuda/nvvm/libdevice/libdevice.10.bc				usr/lib/nvidia-cuda-toolkit/libdevice/

cuda/version.txt						usr/lib/cuda/

cuda/extras/Sanitizer/include/					usr/lib/nvidia-cuda-toolkit/Sanitizer/
cuda/extras/Sanitizer/libsanitizer-public.so			usr/lib/nvidia-cuda-toolkit/Sanitizer/
